# Generated by Django 5.2.17 on 2026-09-21 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=120)),
                ("note", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("project", "Project"),
                            ("publication", "Publication"),
                            ("other", "Other"),
                        ],
                        default="event",
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="activities/"),
                ),
                ("link", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=240)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("about", "About Boristene"),
                            ("events", "Events & Activities"),
                            ("join", "Getting Involved"),
                            ("donations", "Donations & Tax Benefits"),
                            ("project", "Projects"),
                        ],
                        default="about",
                        max_length=30,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="MediaMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outlet", models.CharField(max_length=180)),
                ("headline", models.CharField(blank=True, max_length=220)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("article_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-published_at", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("logo_url", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="partners/"),
                ),
                ("website_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "short_description",
                    models.TextField(
                        help_text="Short text shown on the project card.",
                        verbose_name="Card description",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The main text shown after visitors open “More details”.",
                        verbose_name="Full description",
                    ),
                ),
                (
                    "date_label",
                    models.CharField(
                        blank=True,
                        help_text="Free text supports date ranges and notes.",
                        max_length=120,
                        verbose_name="Date",
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=180)),
                (
                    "goal",
                    models.TextField(
                        blank=True,
                        help_text="Shown in the project facts on the full page.",
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        help_text="For example: “fundraising target — €70,000”.",
                        max_length=180,
                    ),
                ),
                (
                    "partners",
                    models.TextField(
                        blank=True, help_text="Separate names with commas."
                    ),
                ),
                (
                    "participants",
                    models.TextField(
                        blank=True, help_text="Separate names with commas."
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        help_text="Optional result, award, or next milestone.",
                    ),
                ),
                (
                    "website_text",
                    models.TextField(
                        blank=True,
                        help_text="A highlighted editorial note displayed on the full project page.",
                        verbose_name="Website text",
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("registration_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "Current"), ("past", "Past")],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("role", models.CharField(max_length=160)),
                ("bio", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("date", models.DateField(blank=True, null=True)),
                ("date_label", models.CharField(blank=True, max_length=80)),
                ("location", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="landing.project",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=180)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="landing.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
