# Generated by Django 5.2.17 on 2026-09-21 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediamention",
            options={
                "ordering": ["display_order", "-published_at", "-created_at"],
                "verbose_name": "Media mention",
                "verbose_name_plural": "Media mentions",
            },
        ),
        migrations.AddField(
            model_name="mediamention",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mediamention",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="Short summary shown on the media card.",
                verbose_name="Short description",
            ),
        ),
        migrations.AddField(
            model_name="mediamention",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Show on website"),
        ),
        migrations.AddField(
            model_name="mediamention",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Featured"),
        ),
        migrations.AddField(
            model_name="mediamention",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("interview", "Interview"),
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("story", "Story"),
                ],
                default="article",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="mediamention",
            name="article_url",
            field=models.URLField(blank=True, verbose_name="Article URL"),
        ),
        migrations.AlterField(
            model_name="mediamention",
            name="display_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display order"),
        ),
        migrations.AlterField(
            model_name="mediamention",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Article or interview title.",
                max_length=300,
                verbose_name="Headline",
            ),
        ),
        migrations.AlterField(
            model_name="mediamention",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="Uploaded image"
            ),
        ),
        migrations.AlterField(
            model_name="mediamention",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="External image URL"),
        ),
        migrations.AlterField(
            model_name="mediamention",
            name="outlet",
            field=models.CharField(
                help_text="For example: Ukrinform, Rai News, Corriere della Sera.",
                max_length=180,
                verbose_name="Media outlet",
            ),
        ),
        migrations.AlterField(
            model_name="mediamention",
            name="published_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Publication date"
            ),
        ),
    ]
